# Copyright 2024 The Forgejo Authors
# SPDX-License-Identifier: MIT

name: requirements

on:
  pull_request:
    types:
      - labeled
      - edited
      - opened
      - synchronize

jobs:
  merge-conditions:
    if: vars.ROLE == 'forgejo-coding'
    runs-on: docker
    container:
      image: 'data.forgejo.org/oci/node:22-bookworm'
    steps:
      - name: Debug output
        run: |
          cat <<'EOF'
          ${{ toJSON(github) }}
          EOF
      - name: Missing test label
        if: >
          !(
            contains(toJSON(github.event.pull_request.labels), 'test/present')
            || contains(toJSON(github.event.pull_request.labels), 'test/not-needed')
            || contains(toJSON(github.event.pull_request.labels), 'test/manual')
          )
        run: |
          echo "A team member must set the label to either 'present', 'not-needed' or 'manual'."
          exit 1
      - name: Missing manual test instructions
        if: >
          (
            contains(toJSON(github.event.pull_request.labels), 'test/manual')
            && !contains(toJSON(github.event.pull_request.body), '# Test')
          )
        run: |
          echo "Manual test label is set. The PR description needs to contain test steps introduced by a heading like:"
          echo "# Testing"
          exit 1
