name: issue-labels

on:
  pull_request_target:
    types:
      - edited
      - synchronize
      - labeled

env:
  RNA_VERSION: v1.2.5 # renovate: datasource=gitea-releases depName=forgejo/release-notes-assistant registryUrl=https://code.forgejo.org

jobs:
  release-notes:
    if: ( vars.ROLE == 'forgejo-coding' ) && contains(github.event.pull_request.labels.*.name, 'worth a release-note')
    runs-on: docker
    container:
      image: 'data.forgejo.org/oci/node:22-bookworm'
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v4

      - name: event
        run: |
          cat <<'EOF'
          ${{ toJSON(github.event.pull_request.labels.*.name) }}
          EOF
          cat <<'EOF'
          ${{ toJSON(github.event) }}
          EOF

      - uses: https://data.forgejo.org/actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: false

      - name: apt install jq
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq
          apt-get -q install -y -qq jq

      - name: release-notes-assistant preview
        run: |
          go run code.forgejo.org/forgejo/release-notes-assistant@$RNA_VERSION --config .release-notes-assistant.yaml --storage pr --storage-location ${{ github.event.pull_request.number }}  --forgejo-url $GITHUB_SERVER_URL --repository $GITHUB_REPOSITORY --token ${{ secrets.RELEASE_NOTES_ASSISTANT_TOKEN }} preview ${{ github.event.pull_request.number }}
