// Copyright 2022 The Gitea Authors. All rights reserved.
// SPDX-License-Identifier: MIT

package i18n

import (
	"encoding/json"
	"fmt"
	"html/template"
	"slices"

	"code.gitea.io/gitea/modules/log"
	"code.gitea.io/gitea/modules/setting"

	goi18n "github.com/nicksnyder/go-i18n/v2/i18n"
	"golang.org/x/text/language"
)

// This file implements the static LocaleStore that will not watch for changes

type locale struct {
	store       *localeStore
	langName    string
	idxToMsgMap map[int]string // the map idx is generated by store's trKeyToIdxMap

	bundle           *goi18n.Bundle
	localizer        *goi18n.Localizer
	newStyleMessages map[string]*goi18n.Message
	pluralRule       *PluralFormRule
}

var _ Locale = (*locale)(nil)

type localeStore struct {
	// After initializing has finished, these fields are read-only.
	langNames []string
	langDescs []string

	localeMap     map[string]*locale
	trKeyToIdxMap map[string]int

	defaultLang string
}

// NewLocaleStore creates a static locale store
func NewLocaleStore() LocaleStore {
	return &localeStore{localeMap: make(map[string]*locale), trKeyToIdxMap: make(map[string]int)}
}

/* A note about pluralization rules.
 * go-i18n supports plural rules in theory.
 * In practice, it relies on another library that hardcodes a list of common languages
 * and their plural rules, and does not support languages not hardcoded there.
 * So we pretend that all languages are English and use our own function to extract
 * the correct plural form for a given count and language.
 */

// AddLocaleByIni adds locale by ini into the store
func (store *localeStore) AddLocaleByIni(langName, langDesc string, pluralRule *PluralFormRule, source, moreSource []byte) error {
	if _, ok := store.localeMap[langName]; ok {
		return ErrLocaleAlreadyExist
	}

	store.langNames = append(store.langNames, langName)
	store.langDescs = append(store.langDescs, langDesc)

	l := &locale{store: store, langName: langName, idxToMsgMap: make(map[int]string), pluralRule: pluralRule}
	store.localeMap[l.langName] = l

	l.bundle = goi18n.NewBundle(language.English)
	l.bundle.RegisterUnmarshalFunc("json", json.Unmarshal)
	l.newStyleMessages = map[string]*goi18n.Message{}
	l.localizer = goi18n.NewLocalizer(l.bundle, "en")

	iniFile, err := setting.NewConfigProviderForLocale(source, moreSource)
	if err != nil {
		return fmt.Errorf("unable to load ini: %w", err)
	}

	for _, section := range iniFile.Sections() {
		for _, key := range section.Keys() {
			var trKey string
			// see https://codeberg.org/forgejo/discussions/issues/104
			//     https://github.com/WeblateOrg/weblate/issues/10831
			// for an explanation of why "common" is an alternative
			if section.Name() == "" || section.Name() == "DEFAULT" || section.Name() == "common" {
				trKey = key.Name()
			} else {
				trKey = section.Name() + "." + key.Name()
			}
			idx, ok := store.trKeyToIdxMap[trKey]
			if !ok {
				idx = len(store.trKeyToIdxMap)
				store.trKeyToIdxMap[trKey] = idx
			}
			l.idxToMsgMap[idx] = key.Value()
		}
	}

	return nil
}

func (store *localeStore) AddToLocaleFromJSON(langName string, source []byte) error {
	locale, ok := store.localeMap[langName]
	if !ok {
		return ErrLocaleDoesNotExist
	}

	messageFile, err := locale.bundle.ParseMessageFileBytes(source, "en.json")
	if err == nil {
		for _, msg := range messageFile.Messages {
			locale.newStyleMessages[msg.ID] = msg
		}
	}

	return err
}

func (l *locale) LookupPlural(trKey string, count any) string {
	msg, ok := l.newStyleMessages[trKey]
	if !ok {
		return ""
	}

	pluralForm := (*l.pluralRule)(count.(int))
	switch pluralForm {
	case PluralFormZero:
		return msg.Zero
	case PluralFormOne:
		return msg.One
	case PluralFormTwo:
		return msg.Two
	case PluralFormFew:
		return msg.Few
	case PluralFormMany:
		return msg.Many
	case PluralFormOther:
		return msg.Other
	}

	log.Error("Invalid plural form index %d for count %d", pluralForm, count)
	return ""
}

func (store *localeStore) HasLang(langName string) bool {
	_, ok := store.localeMap[langName]
	return ok
}

func (store *localeStore) ListLangNameDesc() (names, desc []string) {
	return store.langNames, store.langDescs
}

// SetDefaultLang sets default language as a fallback
func (store *localeStore) SetDefaultLang(lang string) {
	store.defaultLang = lang
}

// Locale returns the locale for the lang or the default language
func (store *localeStore) Locale(lang string) (Locale, bool) {
	l, found := store.localeMap[lang]
	if !found {
		var ok bool
		l, ok = store.localeMap[store.defaultLang]
		if !ok {
			// no default - return an empty locale
			l = &locale{store: store, idxToMsgMap: make(map[int]string)}
		}
	}
	return l, found
}

func (store *localeStore) Close() error {
	return nil
}

func (l *locale) TrString(trKey string, trArgs ...any) string {
	format := trKey
	found := false

	if l.localizer != nil {
		if msg, err := l.localizer.Localize(&goi18n.LocalizeConfig{MessageID: trKey}); err == nil {
			format = msg
			found = true
		}
	}

	if !found {
		// First fallback: old-style translation
		idx, ok := l.store.trKeyToIdxMap[trKey]
		found := false
		if ok {
			if msg, ok := l.idxToMsgMap[idx]; ok {
				format = msg // use the found translation
				found = true
			}
		}

		if !found {
			// Second fallback: new-style default language
			if defaultLang, ok := l.store.localeMap[l.store.defaultLang]; ok {
				msg, err := defaultLang.localizer.Localize(&goi18n.LocalizeConfig{MessageID: trKey})
				if err == nil {
					format = msg
				} else {
					// Third fallback: old-style default language
					if msg, ok := defaultLang.idxToMsgMap[idx]; ok {
						format = msg
						found = true
					}
				}
			}

			if !found {
				log.Error("Missing translation %q", trKey)
			}
		}
	}

	msg, err := Format(format, trArgs...)
	if err != nil {
		log.Error("Error whilst formatting %q in %s: %v", trKey, l.langName, err)
	}
	return msg
}

func PrepareArgsForHTML(trArgs ...any) []any {
	args := slices.Clone(trArgs)
	for i, v := range args {
		switch v := v.(type) {
		case nil, bool, int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64, template.HTML:
			// for most basic types (including template.HTML which is safe), just do nothing and use it
		case string:
			args[i] = template.HTMLEscapeString(v)
		case fmt.Stringer:
			args[i] = template.HTMLEscapeString(v.String())
		default:
			args[i] = template.HTMLEscapeString(fmt.Sprint(v))
		}
	}
	return args
}

func (l *locale) TrHTML(trKey string, trArgs ...any) template.HTML {
	return template.HTML(l.TrString(trKey, PrepareArgsForHTML(trArgs...)))
}

func (l *locale) TrPluralString(trKey string, count any, allowFallbackToDefaultLang bool, trArgs ...any) (template.HTML, error) {
	message := l.LookupPlural(trKey, count)

	if message == "" {
		if !allowFallbackToDefaultLang {
			return template.HTML(""), ErrTranslationDoesNotExist
		}

		defaultLang, ok := l.store.localeMap[l.store.defaultLang]
		if !ok {
			return template.HTML(""), ErrLocaleDoesNotExist
		}

		message := defaultLang.LookupPlural(trKey, count)
		if message == "" {
			return template.HTML(""), ErrTranslationDoesNotExist
		}
	}

	message, err := Format(message, PrepareArgsForHTML(trArgs...)...)
	if err != nil {
		log.Error("Error whilst formatting %q in %s: %v", trKey, l.langName, err)
	}
	return template.HTML(message), nil
}

// HasKey returns whether a key is present in this locale or not
func (l *locale) HasKey(trKey string) bool {
	idx, ok := l.store.trKeyToIdxMap[trKey]
	if !ok {
		return false
	}
	_, ok = l.idxToMsgMap[idx]
	return ok
}
